---
framework: mocha
tier: medium

postMerge:
  pattern: 
    - "./test/**/*.spec.ts"

preMerge:
  pattern:
    - "./test/**/*.spec.ts"
preRun:
     command:
        - npm ci
postRun:
     command:
        - node --version
parallelism : 1
version: 1.0.1
